name: CI, Tests and Code Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-snyk:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Instala dependencias y ejecuta los tests del backend
      - name: Install & Test Backend
        run: |
          cd backend
          npm install
          npm test

      # 4. Instala dependencias y ejecuta los tests del frontend
      - name: Install & Test Frontend
        run: |
          cd frontend
          npm install
          npm test

      # 5. Ejecuta Snyk en modo SARIF para todos los proyectos (backend y frontend)
      - name: Run Snyk scan for SARIF output
        uses: snyk/actions/node@master
        with:
          command: test
          args: '--sarif-file-output=snyk.sarif --all-projects'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true  # Para asegurarnos de que se suba el archivo SARIF aun si Snyk detecta vulnerabilidades

      # 6. Sube el archivo SARIF a GitHub Code Scanning
      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
